### ISSUE TITLE
Bump libraries to latest version

### ISSUE THREAD

**Issue by tacman** [themeselection/sneat-html-admin-template-free#6]
> Version: v1.0.0

## Feature Requirement
Since bootstrap 5.2 and jQuery 3.6 are out now, can you bump the versions of those packages?  Likely popper will need to be bumped too.

I attempted to do it on my fork, but ran into this:

```
Error: Command failed: sass scss:/home/tac/survos/themes/sneat-html-admin-template-free/assets/vendor/css fonts:/home/tac/survos/themes/sneat-html-admin-template-free/assets/vendor/fonts libs:/home/tac/survos/themes/sneat-html-admin-template-free/assets/vendor/libs --no-source-map
Error: Undefined variable.
   ╷
20 │   @each $color, $value in $theme-colors-rgb {
   │                           ^^^^^^^^^^^^^^^^^
   ╵
  node_modules/bootstrap/scss/_root.scss 20:27  @import
  scss/_bootstrap.scss 7:9                      @import
  scss/core.scss 1:9                            root stylesheet

    at ChildProcess.exithandler (child_process.js:390:12)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:532:15)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    at Process.callbackTrampoline (internal/async_hooks.js:131:17)
```

**Comment by ajaypatelaj** [comment]
Hello @tacman,

Thanks for using our theme and getting back to us. 
Yes, bootstrap 5.2 is out already and we're planning to upgrade it with their CSS variables support.

We would love to integrate those all changes and it may take some time but definitely, we will consider it with dependencies too (all third party). 


Cheers~
