### ISSUE TITLE
Inf Libs DataTables

### ISSUE THREAD

**Issue by WillsMasthers** [themeselection/sneat-html-admin-template-free#9]
I have tried to implement the lib DataTable.min.js
But I've only gotten it to throw an error in the console

localhost/proyect\libs\DataTables/datatables.min.css
localhost/proyect\libs\DataTables/datatables.min.js

Uncaught TypeError: Cannot read properties of undefined (reading 'value')
     at datatables.min.js:229:96
     at datatables.min.js:64:299
     at datatables.min.js:64:326

I don't know, if I'm implementing it wrong, or it should be done in another way

**Comment by monab** [comment]
Hi @WillsMasthers,

Thanks for getting in touch with us!!
Can you please check our downloaded package and in the live demo once and let me know how it works with you?
If it's there please share live demo URL for the same.

Awaiting to hear from you :)

Stay Safe!!
